# ================= Application =================
spring.application.name=twicenice-backend

# ================= PostgreSQL =================
# Use Render environment variables
spring.datasource.url=${SPRING_DATASOURCE_URL}       # e.g., jdbc:postgresql://twicenice-db.render.com:5432/twicenice-db
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}   # e.g., twicenice_user
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}   # e.g., WjBcngNf9DLxW2yNAj0Yyjj8XVtBYoBg

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ================= Razorpay =================
razorpay.key_id=${RAZORPAY_KEY_ID}
razorpay.key_secret=${RAZORPAY_KEY_SECRET}

# ================= Logging =================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#==================cloudinary ==================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
# ================= File Upload =================
spring.mvc.static-path-pattern=/images/**
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=uploads
file.access-path=/images/**

# ================= Hikari Connection Pool =================
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=10000
